<?php
/**
 * Created by PhpStorm.
 * User: Lazytech
 * Date: 2019/1/5
 * Time: 16:24
 */

namespace addons\doger\controller;


use addons\doger\library\Auth;
use think\Config;

class Base extends Api
{
    protected $noNeedLogin = ['login'];
    protected $noNeedRight = ['*'];

    protected $allowFields = ['id','nickname','avatar','session_key','is_new','status','gender','cert_status','applytimes'];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Config::set('default_return_type', 'json');
        Auth::instance()->setAllowFields($this->allowFields);
    }
}